#!/bin/bash
#username="USERNAME"
#password="PASSWORD"
#echo
#curl -u $username:$password --silent #"https://mail.google.com/mail/feed/atom" | grep #-oPm1 "(?<=<title>)[^<]+" | sed '1d'

#then
#chmod +x check_email.sh
#bash check_email.sh

#now run this commnd in any script by referencing it or make tit  a shortcut key
