#!/bin/sh
echo '1'
echo '2'
read os
case $os in
  1) echo 'one';
     sleep 2;;
  2) echo 'two';
     sleep 2;;
esac
echo 'part one done'
sleep 2
if [ $os == 1 ]
then
  echo 'os det' && sleep 2
  echo 'work? y/n'
  read n
  case $n in
    y) echo 'fuck yeah';
       sleep 2;;
    n) echo 'still fuck yeah';
       sleep 2;;
  esac
fi
echo '2 done'
sleep 3
