#!/bin/sh
clear
sudo apt update
sudo apt -y upgrade
sudo apt -y install zsh
echo 'this install needs to be completed in steps'
echo 'each step will be explained as you go'
echo 'to install zsh packages press y to exit press n'
echo ' '
echo 'only run the following commands if directed to do so'
echo ' '
echo 'press 2 to proceed to step 2'
echo 'press 3 to proceed to step 3'
echo 'press f to proceed to fix #1'
read n
case $n in
  y) sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)";
     echo 'please restart terminal then run run this file again and select step 2';
     sleep 5;;
  n) echo 'okay exiting';
     sleep 2;
     exit;;
  2) git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting;
     echo 'please restart the terminal then run this script and select step 3';
     echo ' ';
     echo 'if syntax is not working correctly after restart. run this script again';
     echo 'and select f for fix #1 at the menu otherwise select 3 to proceed to step 3';
     sleep 6;;
  3) git clone --depth=1 https://github.com/romkatv/powerlevel10k.git $ZSH_CUSTOM/themes/powerlevel10k;
     echo 'please change your theme to "powerlevel10k/powerlevel10k" then restart terminal';
     echo 'press m to open your zshrc file for you to modify';
     echo 'or press x to exit';
     read n
     case $n in
       m) sudo nano $HOME/.zshrc;;
       x) exit;;
     esac
  f) echo 'some systems require you to manually add zsh-syntax-highlighting';
     echo 'to the list of plugins. your zsh will automatically open for you to modify';
     echo 'scroll down till you reach the plugins section and edit the entry to read';
     echo 'plugins=(git zsh-syntax-highlighting)';
     echo 'then restart terminal';
     sleep 6;
     nano $HOME/.zshrc;;
esac
echo ' '
echo 'if you want to install something else press y'
echo 'or press x to exit'
read n
case $n in
  n) echo 'exiting...';;
  y) bash $HOME/installer/start.sh;;
  *) echo 'exiting...';;
esac
sleep 2
